Move examples to a subfolder; add lex&parse example using lex library.
cznic/golex pull request #12
Opened 2017-07-13 19:46 UTC by snakeru

This example uses the lex.Lexer instead of a custom one. The reasons for the pull are two-fold:
1) There is no lexer+parser example for the languages with keywords yet. The most evolved example (calc) uses only operations and numbers, no keywords
2) Ability to mark the lexed candidate and then unread bytes on abort. I have lost the whole day before I realized what the problem was (the calc example is too primitive). Hopefully someone else will use my example.
Specifically I was trying to parse a C-like language that features divisions (single slash) and comments until end of the line (double slash).

2017-07-13 20:13 UTC, cznic requested changes
See inline notes. Also, please add yourself to the AUTHORS and/or CONTRIBUTORS file. Thank you.

2017-07-13 20:13 UTC, cznic commented on examples/c-like/example.l
> +  "bufio"
Please gofmt.

2017-07-13 20:13 UTC, cznic commented on examples/c-like/example.l
> +  out := new(bytes.Buffer)
Please use TokenBytes() instead.

2017-07-13 20:14 UTC, cznic commented on examples/c-like/example.l
> +  "bufio"
Err, this is not a .go file. Feel free to ignore the previous comment.

2017-07-13 20:39 UTC, snakeru commented on examples/c-like/example.l
> +  out := new(bytes.Buffer)
Done.

2017-07-13 20:39 UTC, snakeru commented on examples/c-like/example.l
> +  "bufio"
Ack.

2017-07-13 20:42 UTC, snakeru commented
Just in case my 'Done' comments already propagated to you: please bare with me, it's the first time I use github for code reviews. I am currently researching what is the proper way to git commit --amend here.

2017-07-13 20:43 UTC, cznic commented
> Just in case my 'Done' comments already propagated to you: please bare with me, it's the first time I use github for code reviews.

No problem and thanks for the PR!

2017-07-13 21:09 UTC, snakeru commented
I amended my commit and did a force-push (hopefully that's the right way to do it - I was not able to find a clear instruction how to make changes and keep just a single commit).
Please take another look. The correct commit is bf73...

Thank you for the TokenBytes() hint! I was able to delete a few lines.

2017-07-13 21:21 UTC, cznic approved these changes
LGTM, thank you. Please merge to the master branch.

2017-07-14 06:54 UTC, merged

2017-07-14 06:54 UTC, snakeru commented
Thanks! Done.

2017-07-14 09:37 UTC, cznic commented
Thank you!